### ISSUE TITLE
Main To-Do List

### ISSUE THREAD

**Issue by ghost** [ijyliu/ECMA-31330-Project#65]
Paul:

- [x] Add IV to My Simulation Code (as another option to the existing options)
- [x] Review Isaac's code, so that it matches with the simulation code
- [x] Add simulation output with n=2,000
- [x] Make sure paper stays within 12 pages (probably trim some of the language)
- [x] Take log of variables to see how the different methods perform
