### ISSUE TITLE
Comments on Simulation Code

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#79]
- [x] according to #64 we should be taking the log of the true variable and rescale, then do the comparison. But at the moment we are taking e to the power of the mismeasured variable as out transform. I mean, I guess doing the exponential give us a change in the order of magnitude of items as we desire. 
- [x] Another question is whether to do the logging/transformation before or after adding in the error. I think in the current code it's after the error has been added, which seems to make sense; otherwise you would need to scale/fiddle with the error structure a lot. Though the comment in #64 said to transform the true variable.
- [x] I don't see the rescaling (by -1 perhaps) mentioned in #64? Except for maybe in the IV formula? Not clear to me what that -1 is.
